### ISSUE TITLE
Firmware Update - Not working

### ISSUE THREAD

**Issue by pablorq** [arduino-libraries/MKRWAN_v2#9]
Hi,

MKRWANFWUpdate_standalone from MKRWAN_v2.h does nothing, just print "Press a key to start FW update".

Modified the baud rate to 57600 as seen on [this post](https://forum.arduino.cc/index.php?topic=713067.msg4885912#msg4885912) in the Arduino forum but it didn't works, always the same message on the serial terminal.

Firmware update and First configuration works ok with MKRWAN.h library.

Any ideas?

**Comment by facchinm** [comment]
Hi @pablorq ,
I think you need the latest version from git (still unreleased) since it contains [this](https://github.com/arduino-libraries/MKRWAN_v2/commit/3c9c2a44ab719648fa6c36366eaa122dd1113c13) fix.
I'll proceed in publishing the new one that will be available via library manager in the next few hours :slightly_smiling_face:
